services:
  webtop-grass:
    build: .                           # Tells Compose to look for the Dockerfile in this folder
    container_name: webtop-grass
    ports:
      - "3002:3000"                    # Access the desktop via your web browser
    environment:
      - TZ=Europe/Paris                # Timezone
    cap_add:
      - NET_ADMIN   # Allows the app to manage network interfaces
      - NET_RAW
    shm_size: "1gb"                    # Prevents web browsers/heavy apps from crashing inside Docker
    restart: unless-stopped